In [2]:
import pandas as pd

score = pd.read_csv('data/score.csv', index_col="과목")
score

     1반  2반  3반  4반
과목
파이썬  45  44  73  39
DB   76  92  45  69
자바   47  92  45  69
크롤링  92  81  85  40
Web  11  79  47  26

In [4]:
#최대값에서 최소값을 빼는 함수를 정의해서 데이터프레임에 적용
def max_min(x):
    return x.max() - x.min()

In [9]:
#데이터프레임에 사용자정의함수를 적용하는 방법 -> apply 
score.apply(max_min, axis=0) # 행끼리 비교
score.apply(max_min, axis=1) # 열끼리 비교

과목
파이썬    34
DB     47
자바     47
크롤링    52
Web    68
dtype: int64

In [10]:
date_df = pd.DataFrame({"yyyy-mm-dd":['2003-03-13','2017-10-20','2022-05-28']},
            columns = ['yyyy-mm-dd'])
date_df

   yyyy-mm-dd
0  2003-03-13
1  2017-10-20
2  2022-05-28

In [11]:
#연도만을 가져올 수 있는 사용자 점의 함수 정의하기
def extract_year(x):
    return x.split('-')[0]

In [14]:
date_df['tear'] = date_df['yyyy-mm-dd'].apply(extract_year)

In [15]:
date_df

   yyyy-mm-dd  tear
0  2003-03-13  2003
1  2017-10-20  2017
2  2022-05-28  2022