# Transformer (BERT (Bidirectional Encoder Representations from Transformers))

### 시퀀스-투-시퀀스(Sequence-to-Sequence)
  - 번역기에서 대표적으로 사용되는 모델
  - 인코더와 디코더라는 두 개의 모듈로 구성
  - 인코더 :  입력 문장의 모든 단어들을 순차적으로 입력받은 뒤에 마지막에 이 모든 단어 정보들을 압축해서 하나의 벡터로 만듬 (context vector)
  - 디코더 : 컨텍스트 벡터를 받아서 번역된 단어를 한 개씩 순차적으로 출력

<center>  
<img src="https://arome1004.cafe24.com/images/deeplearning/encoder_decoder.png" width=60%>   
</center>

- RNN에 기반한 seq2seq 모델의 두 가지 문제
  - 하나의 고정된 크기의 벡터에 모든 정보를 압축하려고 하니까 정보 손실이 발생
  - RNN의 고질적인 문제인 기울기 소실(vanishing gradient) 문제가 존재

### Transformer
  - 필요한 것은 주의 집중(Attention is All You Need) 논문으로 2017년 발표
  - 순환과 컨볼루션을 완전히 배제하고 오로지 Attention 메커니즘에만 기반을 둔 새롭고 단순한 신경망 아키텍처

  - 인코더와 디코더로 구성
  - 인코더
    - 트랜스포머는 하이퍼파라미터인 num_layers 개수의 인코더 층을 쌓음
    - 하나의 인코더 층은 크게 셀프 어텐션과 피드 포워드 신경망의 2개의 서브층(sublayer)으로 구성
      - Multi-head Self-Attention : 셀프 어텐션을 병렬적으로 사용
      - Position-wise FFNN : 일반적인 피드 포워드 신경망
    - 인코딩의 출력은 디코더로 전달

  - 디코더
    - num_layers 개수의 디코더 층을 쌓음  
    - 인코더에서 보낸 출력을 디코더 층의 연산에 사용
    - 디코더는 3개 층으로 구성
      - Masked Multi-head Self-Attention (Self Attention과 Look-ahead mask): 현재 시점의 예측에서 현재 시점보다 미래에 있는 단어들을 참고하지 못하도록 룩-어헤드 마스크(look-ahead mask)를 사용
        - 트랜스포머는 문장 행렬로 입력을 한 번에 받으므로 현재 시점의 단어를 예측하고자 할 때, 입력 문장 행렬로부터 미래 시점의 단어까지도 참고할 수 있는 현상이 발생
      - Multi-head Self-Attention (Encoder-Decoder Attention) : 멀티 헤드 어텐션을 수행
      - Position-wise FFNN

<center>  
<img src="https://arome1004.cafe24.com/images/deeplearning/transformer_attention_overview.png" width=60%>   
</center>

- 디코더의 Multi-head Attention
  - 인코더의 입력이 한글이고 디코더의 출력이 영어인 경우
  
<center>  
<img src="https://arome1004.cafe24.com/images/deeplearning/self_attension2.png" width=40%>   
</center>

- Masked Multi-head Attension
  - 학습과정에서는 인코더에 "어제 카페 갔다 거기 사람 많다"가, 디코더에 입력된 상황이라면 트랜스포머 모델은 다음 영어 단어 I를 맞추도록 학습
  - 하지만 학습 과정에서 모델에 이번에 맞춰야할 정답인 I를 알려주게 되면 학습하는 의미가 없어짐
  - 따라서 정답을 포함한 미래 정보를 셀프 어텐션 계산에서 제외하게 하는 것
  - 예측할 대상은 확률은 높이고 다른 단어들의 확률은 낮게 조정
  
<center>  
<img src="https://arome1004.cafe24.com/images/deeplearning/self_attension3.png" width=40%>   
</center>

### BERT
- BERT 모형은 2018년 11월 구글이 공개한 인공지능(AI) 언어 모델
- BERT 모형의 특징 : 사전학습, 문맥학습, 파인튜닝
  - (사전학습) 위키피디아 같은 아주 큰 데이터들을 사용하여 '언어 이해' 모델을 사전학습(Pre-training)
  - (문맥학습1) 문장 순서를 학습하여 다음에 나온 문장이 순서에 맞는 문장인지 학습
    - 문장1: 저 남자는 회사에 출근했다
    - 문장2: 회사에 출근하자마자 저 남자는 커피를 끓여 마셨다. (순서가 맞음)
    - 문장3: 저 여자는 퇴근하려 한다.
    - 문장4: 강아지는 예쁘다. (순서가 틀린 문장)

  - (문맥학습2) 양방향으로 학습하여 가려진 단어를 맞춘다.
    - 문장 : 저 남자는 (①)에 출근했다. 회사에 출근하자마자 저 남자는 (②)를 마셨다.
    - ① : 회사 ② : 커피

  - (파인튜닝) 생성된 모델을 최적화하여 새로운 과제를 해결

- 학습 목표
  - 참고
    - 파이토치 : https://velog.io/@fragrance_0/NLP-BERT-실습-예제-네이버-영화-리뷰-감정-분류
    - 케라스 : http://github.com/kimwoonggon/publicservant_AI/blob/master/03_케라스로_버트_빠르게_돌려보기_With_네이버_영화_감성분석_TUTORIAL.ipynb
    
<center>  
<img src="https://arome1004.cafe24.com/images/deeplearning/bert.png" width=40%>   
</center>

In [1]:
# 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# 작업 경로 변경
%cd /content/drive/MyDrive/Colab Notebooks/딥러닝_501

/content/drive/MyDrive/Colab Notebooks/딥러닝_501

- transformer 설치

In [4]:
# 코랩은 설치되어 있음
!pip install -q transformers datasets

# transformers = HuggingFace 라이브러리
#                BERT, GPT 등 모델 불러다 쓸 수 있게 해주는 것

# datasets = HuggingFace 데이터셋 라이브러리
#            학습 데이터 쉽게 불러올 수 있게 해주는 것

- 데이터 새로 불러오기

In [5]:
# 네이버영화리뷰 데이터 불러오기
import pandas as pd

train_data = pd.read_csv('./data/ratings_train.txt', delimiter='\t')
test_data  = pd.read_csv('./data/ratings_test.txt', delimiter='\t')

# 결측치 제거
train_data = train_data.dropna(how='any')
test_data = test_data.dropna(how='any')

# 한글과 공백만 추출, 댓글이 없는 데이터 삭제
train_data["document"] = train_data["document"].str.replace("[^가-힣 ]","", regex=True)
train_data = train_data[train_data['document'].str.strip() != '']

test_data["document"] = test_data["document"].str.replace("[^가-힣 ]","", regex=True)
test_data = test_data[test_data['document'].str.strip() != '']

- 일부 데이터만 사용

In [6]:
import pandas as pd
# 훈련데이터 15만개 -> 다학습시키려면 시간이 오래 걸림 -> 앞, 뒤 1만개씩 2만개 데이터만 사용
train_data2 = pd.concat([train_data.iloc[:10000],
                         train_data.iloc[-10000:]])# 마이너스(-) 기호는 뒤에서부터 센다는 뜻/데이터셋의 맨 마지막부터 역순으로 뒤의 10,000개 행을 가져옴
train_data2

              id                                           document  label
0        9976970                                  아 더빙 진짜 짜증나네요 목소리      0
1        3819312                         흠포스터보고 초딩영화줄오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                          교도소 이야기구먼 솔직히 재미는 없다평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화스파이더맨에서 늙어보이기만 했던 커스틴 던...      1
...          ...                                                ...    ...
149995   6222902                                    인간이 문제지 소는 뭔죄인가      0
149996   8549745                                         평점이 너무 낮아서      1
149997   9311800                      이게 뭐요 한국인은 거들먹거리고 필리핀 혼혈은 착하다      0
149998   2376369                         청춘 영화의 최고봉방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[20000 rows x 3 columns]

- 훈련-검증 데이터 분할

In [7]:
from sklearn.model_selection import train_test_split

# X와 y를 따로 넣지 않고, train_data2라는 데이터프레임(통째로 된 표 하나)을 그대로 집어 넣음
# 표 한 장을 행(Row) 기준으로 8:2로 쪼갬 ➡️ 총 2개 반환 (train_df, val_df)
train_df, val_df = train_test_split(train_data2,
                                    test_size=0.2,# df 하나 넣음 -> 8:2로 쪼개진 2개의 리스트 나옴
                                    random_state=42)

# 문자열 데이터로 명시 후 리스트로 변환
# 허깅페이스 모델이 알아들을 수 있는 형태로 변환해야해서 리스트로 바꾸는 중!
train_texts = train_df['document'].astype(str).tolist()
train_labels = train_df['label'].tolist()
val_texts = val_df['document'].astype(str).tolist()
val_labels = val_df['label'].tolist()

In [8]:
train_df['document']

5947                                    명감독의 졸작 감동이나 재미는 없다
3755                                    올해 최고의 한국영화가 될 것입니다
9040                     극의 힘을 보여주는 영화 이 영화를 보는데 무슨 말이 필요할까
7741                                   타이 쉐리던 타이 쉐리던 타이 쉐리던
6052                                            잘도 이런 미친영화를
                                ...
141179                                      당시에 굉장히 재밌었던 영화
141870    초딩때봤는데잘기억은안나지만최악의영화라는게머릿속에새겨져있다 광구가지금추석때매하도욕을먹...
5440                                             장선우 쓰레기 영화
867                                 별로완전별로마지막빼고 넘 유치하고재미없고
145747                                  첫 분 보고 드는 생각 빨리 꺼야지
Name: document, Length: 16000, dtype: object

In [9]:
train_texts

['명감독의 졸작 감동이나 재미는 없다',
 '올해 최고의 한국영화가 될 것입니다',
 '극의 힘을 보여주는 영화 이 영화를 보는데 무슨 말이 필요할까',
 '타이 쉐리던 타이 쉐리던 타이 쉐리던',
 '잘도 이런 미친영화를',
 ' 재밌게봤었는데 언제봣드라',
 '년전에 봣던 영화인데도 귀자르는 장면은 기억에 남아있는 영화',
 '나도 가 넘 좋더라 그 나이에 그 상황에 겪을 법한 갈등을 잘 그린 영화',
 '봉테일 감독의 명성을 제대로 느낀 영화입니다 물론 주석을 통해 의미들을 명확히 깨닫게 되긴 했지만요',
 '역시 프랑스에는 기대가 안간다는 편견만 만들어준다',
 '우와 점이 없는게 아쉽다',
 '단순한 싸이코물을 벗어난',
 '쇼를해라 쇼',
 '오유분들 이 불건전한 영화의 평점을 내립시다',
 '보고나면 기분좋은 여운이남음',
 '옛날영화를 본건 이 영화가 처음이었다 화질 좋은 영화만 봐서 아무리 작품성이 좋아도 안보는데 이건 정말 보기를 잘했다 러시아라는 국적과는 상관없이 인간의 삶이 잘 묻어나는 작품이었다',
 '지저분하고 무섭지도 않고완전 코미디에 암튼 즈질 영화  점주기도 아꼽넹',
 '개재미없음 막장스토리 어거지 ',
 '아직도 이연걸이 손수건으로 얼굴 가리고 우는 장면은 잊혀 지지가 않는다 ',
 '다시봐도 질리지 않는 영화',
 '특별한 교감과 침묵의 삶 수작이라고 생각되는 최고의 영화였습니다',
 '놀랍도록 예술적이며 날카롭다 이 영화지적할꺼면 그냥 평생 도둑들이나 보시면 될듯',
 '마지막에 조민아 당하는씬 너무 몸사린거 아닙니까 맛배기도 없고 너무하네 우주여신땜에 돈과 시간이 아까움',
 '최고의 작품고립된 공간에서 벌어지는 혈육에 대한 여자들의 광기',
 '끝도 허무하다뻔한 결말을 왜 봐 아돈내나',
 '마지막이 참 좋았는데 스릴있고 이제보니까 외국영화 어두워질때까지를 가져다 쓴거구나 ',
 '한니발은 그냥조연인데 나름 괜찮았다 꽤 괜찮은 스릴러다',
 '공유 정말 잘생겼고 임수정도 이쁘게 나오고 즐길만한 로맨틱코미디 장르가 아니었나하는 생각이 듭니다',
 '단지 좀더 완성된 시나리오의 결집력에 대한 아쉬움이 흠이라면 흠일까',
 '점짜리 코스프레 점짜리 영화',
 '억지스러운 시나리오지루한 전개 편 보다 못한 구성등 편은 안나오는게 나았다망작배우들이 영화보는 눈이 없어서 안타깝다',
 '뭐 하나 건질것 없이 매우 비이성적이며 불쾌해요 이해가 쉽진 않지만 그림이라도 아름다운 류의 컬트영화랑은 또 다릅니다 이해가 상당히 쉬운데 매우 억지스러워요',
 '진짜 웃기고 연기도 잘하고특히 연로배우들 스토리도 좋다',
 '굿중학교 때 봤는데도 잊혀지지 않은 영화',
 '불면증 치료영화 시간아깝다',
 '주말의 명화에서 봤는데 정말 최고다',
 '훌륭한 시나리오 훌륭한 연출 훌륭한 연기',
 '별점 주기도 아깝네요 얼마나 내용이 진부한지 욕 밖에 안나오네요보고 재밌다고 하는 사람 초딩들인가요 죄송해요 너무 화가나서아무 것도 볼게 없습니다 보지 마세요 그냥 티비판짜집기 한거 같네요',
 '아놔 유인나는 매화 존나 귀척 이쁜척 하고 그것밖에 할 줄 모르냐 연기진짜 그러니까 결국 두 남자 사이에서 어장관리만 하는 걸로 보이지 게다가 드라마 내용만 질질 끌고 유인나 캐릭터는 드라마를 위한 연기가 아니라 본인 피알을 위한 연기다',
 '인간의 본성 자기중심적 사고는 관계를 복잡하게 하지만 그 것이 결코 나쁜것은 아니다',
 '나만 죽을수 없다는 건가',
 '나 나영아 ',
 '갠히봤다안보는건데흠',
 '뭐야 대중을 공감시켜야지 감독지혼자만 공감하냐',
 '콜로 형 촬영도 신기하고 생명이라는게 놀라움',
 '엣세이적 아름다운 영화네요',
 '설정이 재밌고 새로운 에피소드 내에서 메인 스토리도 차차 나오는게 재밌음',
 '머야설마설마 했다 진짜로 너무 뻔해서 영화 쩐다',
 '뻔한내용이지만 해피엔딩 기대했는데 마지막에 막장이네',
 '  우울해졌어인생은 말야픽션인 동시에 논픽션이야',
 '오늘 티비로 봤는데 재밌어요 나왔으면 좋겠는데',
 '진짜 보면서 그만볼려다가 억지로참고 봤는데 너무재미없어요안보는게 날듯',
 '어케보죠 궁금함',
 '완전 시간 아깝다',
 '이런것도 영화냐냐냐',
 '코미디로볼영화가아님대한민국남자반성좀해요격투기남자친구사겨본한사람으로서',
 '꼭 보세요인생 처음으로 인터넷에 평점 답니다이거 실화라는 말 들었는데 정말인가요 대학교 미국문화 관련 교양시간 살짝 배웠던 영화인데 이제야 제대로 다봤어요 용감함 얻고 가요',
 '최악의영화 ',
 '링 시리즈중 최고다 사다코에 대해 알려주는편이라서 흥미롭고 무섭게봤다',
 '솔직히 분신사바도 노잼이었음',
 '이런 영화 다시는 안나오겠지그때 시절을 잘나타내주었던거같아요 ',
 '황당해서 기가 막히다',
 '와우 시걸형님 짱',
 '한줄분석이 영화를 가장 좋아하는 그룹은 대 여자입니다 하 이런 쓰레기년들 주진모 송승헌 나왔다고 전설의 명화를 더럽힌 이딴 쓰레기 허세 겉멋영화를 점넘게 올려놓냐',
 '의도는 알겠는데 뭐 이리 말만 많냐 좀 정돈하면 잘될꺼 같구만 영',
 '당시엔 인기 있었던 영화긴 하지만 왜이렇게 점수가 높은거지',
 '나는 굉장히 재미있게 봤다 타짜보다 더 강렬하던데 배우들도 쌈빡하게 연기하고',
 '숫자로만 소통한다는 알바는 사람과의 소통에 큰문제가 있어보이진 않는다 괴짜보단 세상을 아직모르는 아이같은 느낌 전개는 너무 산만하고 문화의 차이인지 주변인물의 반응에 공감하기 힘들다 그닥인영화단 알바는 참 이쁘다 알바의 화장실 문지기하고프다',
 '그 흔한 베드신도 안나옵니다  키스신도 걍 뽀뽀질임  참고만하삼 ',
 '하네',
 '사람으로 길러진 님을 버리고 실험하고 가두었다그 과정이 너무 참혹하고 마음 아프다',
 '아이게공포냐재미없네 그래도 장근석이잘생겨서점드림',
 '마음이치유되는곳 히말라야로',
 '이런영화좀만들지마라',
 '주님께서 부르셔서 제가 여기 있나이다',
 '뭔가알수없는매력에빠져드는 영화',
 '배우의 연기가 스토리를 압도한다',
 '따분하고 공감할 수 없어',
 '상영 내내 즐거웠다',
 '최고 정말 최고다',
 '오랜만에 시간낭비한거 진짜 아깝구나 라는 생각이 드네요 쥐기삘라',
 '영화춘향전을 고발한다 연예가중계에서 정사신을 강요하며 욕하는 정일성촬영감독과 수치심에 울고 정사진을 소스라치며 거부하는 여자주인공의 영상을 봤다 그리고 그상황을 고개돌려 외면하는 임권택감독 살 청소년에게 금정사신을 찍게한 명백한 범죄다',
 '민간인은 볼수 없는영화',
 '흑암에서 빛으로 좋은 영화네',
 '흐지부지한 끝맺음입니다',
 '액션은 내가가장좋아하는장르인데 이건좀아닌듯스토리하나도없고 액션도지나치다못해산만하기까지',
 '배우들은 다 괜찮은데 시청률이 낯아서 아쉬워요',
 '전개 억지스럽고 연출도 조금 산만한듯 소품들도 좀 어색합니다 비행기씬은 어쩔수없다지만',
 '애니를 능가 원작에 충실했다',
 '전후 황폐해진 베를린 인간다운 삶의 조건이 상실된 거리에 어린 영혼이 내던져진다',
 '내가 제일 좋아하는 영화',
 '정말 상업적이니 않은 영화 재미없음',
 '완벽그자체다완벽해진짜',
 '여성입장에서 볼땐 모르겠는대 남자인 내가 보기엔 그냥 합리화 정당화 시키려는 비겁하고 썩 유쾌하지 못한 영화',
 '이건뭐배우들의 발연기덕에 영화에 집중할수가 없다스탭들 촬영 기술수준도 좀 낮은듯한',
 '영화가 다 저질이구만이거 ',
 '말없이 눈물이 뚝뚝',
 '이거 실화였지 아마 ',
 '오랜만에 봤는데 요즘 영화보다도 더 재밌어요 마지막에 미그기가 미사일발사했을때 대신 전투기가 격추당하는 장면은 정말 압권이었습니다',
 '코믹 호러용치고 수작인데 평점 너무 낮다',
 '쓰레기장에 한가운데 분동안 헤매다 나온 기분 절대공감',
 '동성이든 이성이든 인간이 사랑하고 싸우고 살아가는 모습은 비슷비슷하다',
 '스토리 완전오글거림 절대 재미없음 감동전혀없음 쓰레기영화',
 '정소영도 나오네',
 '나의 시간을 빼앗을 뿐아니라 육체적 정신적 충격이 크다이 영화 후유증 개쩜너무 황당해서 말도 안나옴 걍 배우가 아까울 뿐 뛰어넘기하면서 겨우 결말 봄그마저도 어이 걍 강지환이 멋지게 나와서스타일이 견뎌냈음',
 '멋진 영화',
 '거짓말 하는 부분까지만 달콤하다',
 '이병헌의 명품연기',
 '정말 영상하나하나에 감동이 묻어나오는 영화 몇번보아도 질리지 않는 영화',
 '        최강두산베어스  ',
 '신지 새키 전부터 맘에 안들었지만 세상 멸망시켜놓고 또 멸망시키려함 하지 말라는건 죽어도 지 똥고집 부려요 교육못받은새키 그리고 에반게리온 솔직히 무슨 철학적인척 포장하면서 속은 개 모순덩어리 쓰레기 스토리에 허점많은 떡밥들',
 '너무이상',
 '이런걸 영화라고 한심',
 '너무너무너무너무너무너무너무너무너무너무너무너무재미있어요',
 '이 영화를 조금 봤는데 이것이 현실이라는 사실이 너무 안타까웟습니다',
 '평점이 쓸데없이 높네요도데체 와이프가 임신한 이유는 몰까요',
 '처음부터 끝까지 몰입최고',
 '결정적인 부분은 우연에 기댄다 허술하고 현실성 없는 추리도 문제 심리학자가 일은 안하고 탐정놀이하는것도 문제 사람들이 상담받으러 왔다가 사건만 던져주고 가는등설정을 위한 설정 때문에 어이가 없다 직소퍼즐 같은 진부한 소품도 유치',
 '답 안 나오는 영웅 서사시',
 '시대를 초월하는 재미와 작품성',
 '홍은희씨 벨트착용이 너무 잘못됐네요 저건 멘것도 안멘것도 아닌팔에악세서리처럼 걸치셨네요 ',
 '아웅 드디어봤네여 너무 잼께잘봤습니다사람들개인의취향이 각자 다 다른거라지만 이영화를 억지스럽다 그저재미없다시는분들이 저는 조금 이해가지않을정도루 가슴이 뭉클해지구 짠했어요저는 요즘 톰하디영화를 전부 찾아서보구있는데 정말 연기 잘하는배우인거같아요',
 '완전조아요',
 '애니로 안보고 영화로만 처음봣는데 나는 진짜재밋게 봣는데 특히마지막전투씬',
 '마이너리티의냄새  곽지민의 매력',
 '번정도는 본거 같은데 아직도 매년 번씩은 꼭 보는 나만의 영화엽청문의 주제곡과 마지막 장면이 아직도 기억에 남는다 장철감독의 금연자와 철수무정과 비슷한 스토리구성두 남자의 우정을 정말 아름답게 그렸다',
 '다시봐도 질리지 않는 코믹영화',
 '뭐하자는건지',
 '안성기가 김규리에 반하다니 무리수',
 '뭐지 이딴영화는',
 '핵노잼이다 너무 산만하다',
 '의리로 점',
 '아니 영화하기 싫으면 중간에 다른감독한테 넘겨주든가 이게뭐냐',
 '상영종료후 년뒤에 극장판이 나올정도의 초 대작편의 설정오류 수정과 새로운 씬 추가가 주된 볼거리 마마마는 어른들을 위한 애니이다우측의 리뷰를 보고 애들과 함께 볼려고 한 분들에게는 절대로 애들에게 보여줄 작품이 아니라고 강력히 주장한다',
 '쫌 아니다',
 '일분 일초도 쉬지 않고 몰입되고 긴장되고 보고나서도 잊혀지지 않는 정말 영화',
 '최고 여자건남자건 정기적으로봐야할영화',
 '딴말 안함 개도 아깝다',
 '뮤직비됴 짜집기가따로없는 영화과학년생 실습작품이라해도 이보다 쓰레기일수없다',
 '감동과 여운이있는 영화네요 짧지만 깊은 뭔가가 느껴졌어요 혹시  뭔지 알고계시는 분 중간중간 흐르는 멜로디가 너무이쁘네요',
 '욕심은 악을 낳고 악은 또 다른 악을 낳는다절대적인 선은 지구상에 없다',
 '지금봐도 엄청나게 소름이 끼치는 결말 한국 공포영화 희대의 명작이다',
 '안돼 올라갔잖아 안돼 올라갔잖아',
 '방금 영화 보고 나왔는데 마지막 장면에서 싸한 느낌이',
 '점 포커하는 건 뭐 별로 나오지도 않고',
 '정말 열나게 재미없다',
 '재밋어요',
 '재밋고 감동적이에요 ',
 '지금 점수는 너무 적다 충분히 점대는 할수있는 영화 단순액션과 결과주의적인 스토리가 아닌 각 인물의 심정을 느끼면서 보면 충분히 좋은 드라마적요소가 강함 재밌음',
 '아무 생각없이 막 찍어대고 편집으로 이야기 만들어내는 감독',
 '아더왕을 아토리우스라고 부를 때 알아봤어야 했다',
 '웃기지는 않았지만 아버지가 딸에 대한 사랑을 느낄수 있었다',
 '모이아 켈리의 깜직함에 반해서 좋아했던 영화',
 '늦가을 도쿄산책  따뜻하다 모든게',
 '우왕 재밌당 ',
 '전반적으로 무거운 느낌의 영화네요가비의향과맛처럼씁쓸함이 느껴집니다장윤현감독님께서커피부분에관해 신경을 쓰시다보니연출부분에있어서좀 미흡하지않았나싶고 배우들연기력은 괜찮았습니다',
 '등장 인물들이 하나같이 다 매력적인 명작',
 '이걸 조폭미화라고 평가한 사람들은 이 영화를 잘못봐도 한참 잘못 본 거다',
 '남자의 고독을 느끼게 해준다',
 '이런 게 드라마죠 요즘 드라마들은 인기만 끌려고 연애만 해대니',
 '반만 다운받아져 있었기에 미친듯이 휴대폰 결제하고 이어서 보게만든 영화 정말좋다',
 '극전개도 지루하고 줄거리의 실체도 영별루였음 배우들만 아까울뿐완전기대이하',
 '말그대로 뚝방에서 볼영화',
 '강철중 시리즈 완전 잼남',
 '이런 영화도 있구나 분까지는 참고봤는데 더 이상은 볼수 없었다',
 '우리딸들 역시 완전 재미지겜잘봤어요',
 '내용도 좋았고 도 좋았음',
 '오늘의 연애에만 평점 알바가 있는줄 알았더니 ',
 '내용도 별거 없고 임수정도 이쁘게 안나오고 슬프지도 않고 감동도 없고 이건 최악',
 '마지막회가 아쉬운거 빼고 너무 좋았어요 한글이 그렇게 만들어졌는지 전혀 몰랐다가 너무 신기하고 세종대왕님의 업적에 다시한번 놀라게 해준 드라마에요',
 '편보다 별로였',
 '권선징악이란 메세지를 확실하게 전달하는 엽기 막장 블랙 코미디',
 '어디 디비디방에나 있을거같은 영화',
 '몹입도 넘 좋아요 재미있게 봤어요',
 '재 미 없 다',
 '평점 낮게주는 빠가야로들은 이해못하는 영화 최고다최고',
 '나를 설레게했다 아리게했다하더니 마지막엔 둥하고 큰 울림마저 준 고마운 영화',
 '별한개도 아깝다 예쁜 똥느낌 잘짜여진 영화가 아닌듯함 그냥 정신착란증세가 있는 정신병자의 꿈얘기같다 이게 무슨 의도로 만든 영화인지 뭔 개소릴하는지 모르겠다',
 '촬영 감독이 초보인지 장비가 후진 건지 영상이 흔들려서 화면이 매우 불안정',
 '너무재밌게 봤어요',
 '재밌는데 평점이 왜 일케 낮은 거지',
 '잘 보긴 했는데 뭐라고 평가 내리기도 설명하기도 참 뭐라고 말로 표현하기가 힘들었다 뚜렷하게 말할 수 있는건 배우들 연기 정말 잘 하더라 다 못보던 배우들인데',
 '평점보고 빵터지긴 세번째네',
 '연애년인데 저러면 결혼 년차는 죽지못해살듯',
 '중간계 부작의 엔딩 무대를 화려하게 꾸며줬다',
 '디워 편 만들수있으면용 두마리 침대위 베드신 시키게요',
 '재미있어요',
 '별 재미없이 무의미하다',
 '그냥 최고의 드라마 그냥 보세요',
 '그 당시 최고 유명했던 스릴러 몰입도  현재도 스토커같은 사람한테 이 미져리같은  라 칭한다',
 '아이돌이란 타이틀을 따기위해 얼마나 힘든 과정이 필요한지 보여주는 다큐',
 '마음이 편안해지는 영화 ',
 '민감한 소재를 어떻게 이렇게 뻔뻔하게 만들 수 있는지',
 '와 진짜 재밌다 맷데이먼 짱짱맨',
 '기독교인들의 전형적인 정신승리 영화 무신론자랍시고 만든 캐릭터들의 지적수준을 터무니 없게 낮게만들어 어처구니 없는 궤변만 늘어놓고 그게 마치 말이 되는것처럼 만듬 이 영화의 논리대로라면 모든 코믹스 히어로들도 실존한다고 볼수있음',
 '마지막이 좀황당했지만 좋은영화',
 '강추 그건 아니지 양심은 지켜야지 그래도 배우진 빵빵한데 허접한 영화보단 낫다',
 '와',
 '일급살인과 함께 최악의 미국영화이 영화가 왜 리플이개인지 생각해볼것',
 '원작을 안 읽어서인지 처음 기대한 건 유카와와 이시가미의 대결구도였다 기대했던 건 적어서 조금 아쉬웠다 하지만 이런 기대를 잊게 만드는 내용 몰입도 그리고 연기력은 보는 내내 소름을 돋게 만들었다 츠츠미 신이치의 팬이 될 것 같다',
 '때문에 망한영화 시간도 짧았다',
 '내가본 최고의 영화였다',
 '답없네 뭐하는건지',
 '솔직히',
 '정당하게 돈 내고 봤다 그래서 말할수있다 시간을 버렸다',
 '재밌다 추억에 잠긴다',
 '이영화 본사람 있어여 인디안 썸머의 원조에요너무좋은영화',
 '실험하는 가수 데려다가 실험하면 실험영화 되나',
 '악을 응징하는 방법한 차원 높은 악으로',
 '여운이 어마어마하게 남네요',
 '헐충격적이긴 하네처음부터 끝까지 아주 극단적으로만 몰아붙이니',
 '아름답고 먹먹하다 일본의 도시와 시골을 맛깔스럽게 표현했다',
 '원주율 좀 만들어보자',
 '나사가 하나 빠진듯한 영화',
 '에잇 별로네 시간 아까워',
 '산뜻한 패러디 최고의 배우들 영화 자체가 다이아몬드',
 '말로 다 할수 없는 감동 최고의배우 최고의 스토리',
 '매력적이네요',
 '본방사수는못하지만화이팅',
 '웃겨서 죽는줄 알았다',
 '여주인공 이기심의 극치를 보여줌 정말 최악',
 '인간도 결국 외로움을 참지 못하는 동물일 뿐',
 '그냥 정말 조용히 몰입하고 보게되네요',
 '점도 아깝네요 윤주언니때문에 보게 되었는데 정호연씨 에스팀이라고 시즌에 유래없는 패자부활전도 생기고 나머지명 갑자기 탈락시키고  탑까지 가는건가요 으 한국의 청탁문화는 언제사라지련지 쇼에서도 이런모습이니 원',
 '국산은 볼게 못됨 대부분영횐 티비에서 해도 되는데 굳이영화로 만들어 돈 요구하네',
 '이거 완전 재밌어요  난 몇번이나 돌려보고 그랬는데 ',
 '내용이 약간 우울할 순 있지만 영상이 아름답고 볼 만 합니다',
 '이건 또 뭔가요',
 '송혜교은퇴하길 정말 알면알수록 역겨운 연예인 가증스럽고 짜증스럽다 해외부동산 부동산의 여왕인가요 홍보를 위한 착한척 쑈할때도 싫었는데 탈세이후 행각을 보니 뻔뻔그자체',
 '단순한 스토리지만 순순함의매력이 끌리는 영화다',
 '중공군 미화사실에입각하지 않은영화참전용사 호국영령께 죄송스러운 영화',
 '최초이건 아니건 중요하지 않다 그들의 아름다운 도전과 상업성에 반하지 않는 자세가 더 중요하다 생각한다망상녀 당신이 증거가 없다고 하는 저들의 도전을 나는 믿는다 아무나 오를 수 있는 산이라면 저들의 도전은 없었을 것이니까',
 '지루하다 어색한 사투리',
 '짝퉁 직쏘 톱 대신 주사위',
 '최고의 성장 드라마',
 '대박',
 '뭔 개소리야',
 '평점이니까 내마음 작성하는 거지그렇게 안하면 왜달아요참내',
 '재미가 없으면 재미없다 완전 최악이다는 물고늘어진다  같이보자 전나재미있다',
 '평점 낮게 준것들 보나마나 머리빈것들인듯 한국사람들 수준이 다 그렇지 뭐',
 '이영화 평점 왜이리 높지살다살다 영화보고 재미없어서 감상평 남겨보긴 처음이네요 심지어 웃긴 장면하나 없었다는 먼 옛날 심형래 감독의 영화 영구와땡칠이 가 차라리 지금봐도 이 영화보다 재밌을듯',
 '이 유명한들이 다 여기에서나온거구나비디오게임캠패인다깬듯한느낌미니보스깨고 최종보스까지 꿀잼허니잼',
 '역사에 남을 영화다',
 '기본에 충실하면 기분이 좋아진다 안무서워',
 '추억의 명작만화',
 '재미는있었어요 심심할때보면괜찮아요 마지막에 여자가 무녀의목숨이랑바꿔치기해서 살아났을때 감동이였구요 아버지는찾지못했지만 나름 볼만해요',
 '시간이 흘러도 퇴색되지 않는 맛이 있는 영화',
 '기억상실증이라고 말하지 말아줘요 제발',
 '이 영화를 보고 알게 된 중요한 두 가지 첫째 통일의 전단계부터 통일 이후까지 그동안 우리가 조선족의 역할을 생각조차 해 보지 못했다는 것과  전쟁 당시 중공군의 인해전술에 동원된 병사들이 조선족이었다는 사실',
 '막장소재만 없었으면 점 줬다',
 '고릴라 만 그럴듯했다',
 '한국판 제목이랑 광고는 대체 누가 만든거냐',
 '정말재미있고 교훈적인 영화이네요',
 '노력없이 성공을 꿈꾸게하는 미친영화멍청한 여자의 운좋은 인생',
 '영화를 본 후의 이 감동 이 여운을 어떻게 할 수가 없다',
 '완전 재미있었어요 김현주씨 짱',
 '스티븐 시걸은 왜 은퇴하지 않나 영화는 죽어 나가는데',
 '로빈윌리암스 영화는 아이들의 감성을 자극하는 따뜻한 영화가 많은데 이 영화도 그중하나입니다삼가고인의 명복을 빕니다',
 '이승기가 나와서 봤지만 정말 재밌게 본 드라마입니다',
 '점점 지겨워지네 가지고 몇편을 우려먹는지진전이 없어서 보고싶은맘이 없어지네',
 '중국의 힘이 느껴지는 영화',
 '네이버 평점 신뢰 못하는 사람이지만  설래임의 감정을 잊고 있다면 이영화를',
 '무슨뜻인지 이해불가 삼류영화의 끝을 보여줍니다',
 '중꿔는 스케일이 다르당께 눈이 부셔',
 '가족사진 앨범처럼 소중한 곳에 두고 가끔 펼쳐보고 싶은 영화 웃긴데 웃긴데아프다',
 '실제 얼굴과 얼굴을 맞대고 이야기해도 진실을 말하지 않는데 를 통해서는 오죽하겠는가',
 '진짜 너무 대놓고 시청자우롱하는거아님딱봐도 뜨고싶은애들 모아서 연기하는거구만 이미이런스토리진부하자나',
 '강선생 목소리 짱웃겨 예고편 잼있네',
 '시청 시 암 조심하세요',
 '전형적인 유치뽕짝 프랑스영화 새로운장르다 유치뽕짝',
 '내인생 잊혀지지 않은 영화 지금도 빠삐용 주제를 가끔 듣노라면 내가슴 깊은곳에 고독과 살아야겠다는 서러움이 절절하게 끓어오릅니다 아마도 내 인생이 슷비슷비하지 않았나 생각됩니다 물론 빠삐용하고 비교할 수 없지만 조금이나마 내인생을 말해주는 이영화',
 '너무 멋있다',
 '보다가 울컥핫 영화재미도 있고먼가 감동적임',
 '글쎄 한국영화는 보고 나면 남는게 없어기억에서 사라져버려',
 '생각보다 기대 이상으로 재밌게 봤네요 ',
 '우연히본영화나름볼만했다낭만의화신',
 '영화가참 아무양념없이 심해어 구워먹은 그런 느낌 이에요',
 '트레져헌터영화라이만 이건 아니잖아',
 '나 농담않고 이거 영화관에서 번봤다 첨엔 무서웠는데 특이하게 너무너무 잼있다',
 '너무너무 아쉽네요결말 기대했는뎅',
 '영화 개병맛 전혀 현실성도없고 똑같은 장면 너무 많이나옴',
 '몇몇 부분은 볼만하지만 전체적으로 부족하다',
 '장선우에의해 김태연은 버로우 양심있다면 이제 감독하지마라',
 '이건 진짜 까도 까도 깔수 있는 양파계의 명작이다',
 '류승룡이 나오네요',
 '이거이후로 보는드라마가없음',
 '기대안하고봤는데 완전 웃김  완전 재밌네요',
 '김수현작가 작품이라 보기시작했는데 주인공들의 연기 뭔가 끓어당기는 맛이없네',
 '달팽이 때문에 미칠거 같다',
 '한국에 태어난 걸 감사하게 만들어준 영화',
 '신하균씨 참 잘 달리시네요',
 '말도 안되는 평점에 놀라울뿐이고',
 '선정적인 노출과 잔인한 살인씬만이 관객을 위한 친절의 전부라고 생각하고 그 외는 잔뜩 물오른 허세와 돈로만 쳐바른 내멋대로식 철학영화 물론 영화로 책을 쓰고 있으니 영화처럼 뻐기기 좋아하는 것들은 엄청 빨아댈듯',
 '가볍계 보기에 좋다 다음편은 더 재밋길',
 '비추 남자 배우들의 헤어스타일만 봐도 대충 느낌 옴',
 '평점이 점을 넘지 못하는 이유를 모르겠다 본시리즈에 비해서는 부족한 점이 많지만 여전히 높이 평가할 만한 영화이다',
 '내 인생 최고의 드라마 시간의 영화다 모든장면 모든대사가 완벽하다 긴 여운에 아직도 빠담빠담하다',
 '현대판 정무문을 찍고 싶었나 보지만 년대 스토리와 반복되는 패턴의 액션은 지루함을 느끼게 한다',
 '욕망이라는 이름의 전차',
 '이건머',
 '재밌네요 가슴 훈훈하고',
 '이자스민 학력위조 했는데 가만히 냅두는 새누리당 클라스',
 '최악의 쓰레기 오브 쓰레기 영화',
 '소재 좋았고 당시 톱스타였던 김희선의 출연을 감안한다면',
 '스타트랙보다배재미있음',
 '이제할게없어서별걸다하시네염',
 '언론에 비추어진 김정은 체제 아래의 북한을 무조건 적대시했던 오늘날의 남한사회를 다시 되돌아보게 되었다 남북은 정치적 관계를 떠나 한 가족이다 우리는 준비가 되었는가 나는 준비가 되었는가',
 '누가 더 혀짧은가 내기하면 박빙일것같다',
 '버지니아가 데이빗과 클레어를 자유롭게 해주었다',
 '코미디라서 재미있는거 인줄알았는데 너무야했습니다 무슨 세야 ',
 '이게 진리지 내가 페제만큼이나 좋아하는 작품 작품성은 참 끝내주고 기법도 다양해서 참신하다',
 '평생에 이런 영화를 몇번이나 더 볼 수 있을까 최고다',
 '별루',
 '얼마 전에 케이블 에서 우연히 보았는데 최근 에 본 액션 영화 중에서 최고였습니다 극장에서 보지 않은 것이 아쉽네요',
 '한마디로 요약하면 기 승 전 연애',
 '서언이 서준이 분량이 너무 없어서 볼맛 안나고 짜증나네요 인기 많은 삼둥이만 나오게 할꺼면슈퍼맨이돌아왔다가 아니라삼둥이가 돌아왔다로 하시죠',
 '올해 꼭 봐야하는 영화 중에 하나',
 '이름만 들어도 보기싫다',
 '최고다',
 '미소녀 변태 오타쿠들은 당연히 이해할래야 할수없는 수작년도에 이런',
 '이런 영화좀 만들지 말길',
 '이런 허접한 영화로 꼭 알려야하나제대로 기록했더라면',
 '무섭던데요 가끔씩 비추는 귀신들도 무섭고 밤에봤으면 지릴뻔',
 '원표 너를 믿었건만 끝까지 한숨만 나오는 정말 시간아까운 졸작 원표의 미스초이스',
 '정말 뭐가 엉터리인지 모르겠다 하하 간만에 몰입하게 되는 영화',
 '와우 스펙타클 다이나믹',
 '오 굿 엔딩 섹스신 외엔 별로',
 '가장좋아하는 그룹 대여자 덕후들이 시청률 유지해주는구나 ',
 '난 또 내가 몰랐던 영화인줄 알았건만',
 '아이들이 보기엔 좋을지도',
 '너무 어이없고 재미없어서 어처구니 없이 웃음만 나오더라',
 '이것때문에 잘하면 십타쿠 될뻔  에휴 빠져나올수없는 네티 ',
 '이런 감동삶의 희망이 된다',
 '영국 대 판타지라 하면 반지의 제왕과 나니아 연대기 해리포터 를 들 수 있다 책으로 읽어 보시길',
 '기자 평론가라는 넘들은 뭐하는 애들이냐 이렇게 웃긴 영화에 점을 주네 정신나간것들 진짜 웃기다 그냥 아무 생각없이 보다가 빵터졌다',
 '참으로 만만한 신들이로다',
 '영화를 이렇게 독특하게 만들다니 대단하다',
 '다이앤키튼 매력에 푹 빠져 봤다는 중년의  사랑 은은함이 있다',
 '주인공 살에 죽은거 맞냐 얼굴이 완전 대 아저씨같던데',
 '시각적인 딜레마',
 '가슴이 먹먹하다 뷰욕을 왜 이제서야 알게됐을까',
 '전설이죠',
 '퍼펙트 싱어 의도는 뭔지 알겠는데 음정 에만 온 정신이 쏠려있으니까 노래에 집중이 안됨',
 '좋은 소재에 만족할 연출',
 '자극과스릴없이 간만에 이런 은은한영화를보네요 슬펐어요',
 '배우들 연기력 클라스가남다름',
 '쯥',
 '꼭 봐야할 영화 오래 기억 남을것 같아요',
 '다듬으면 정말 괜찮은 영화인데 아쉽네요 전 재밌게 본',
 '별루 ',
 '질질 끄는 거 빼면 점 만점 최고',
 '이렇게 재미없는 영화는 처음이다 코메디라고 해서 봤는데 어디서 웃으라는지 원 한번도 못웃었다 점도 아깝다 감독은 훈훈한 가정애를 만들고 싶었는지는 쉽게 예상할 수 있지만 굳이 근친과 불륜을 말할 필요가 있었을까',
 '높아진 눈높이에 한참 모자른 좀비물',
 '가슴이 찢어질것같다',
 '애니보고 운적 처음이네 아수라 혼자 쓸쓸하고 외롭게 보이는지 와 ',
 '이딴영화 별 개는 머지걍 쓰레기영화 진짜 밑도끝도 없는 사이코 영화인듯',
 '재미있다 재미써천공의성라퓨타 하고 비슷한데 ',
 '진짜 별 개보다 더 줄 수 있는 영화내용도 연기도 최고',
 '별로다 저만화',
 '팝콘만 먹고 바로 나온 영화 어린이들을 위해 만든 영화 같군',
 '한 소녀의 고민을 중심으로 약분동안 지루한 시간들에 연속이다 우리나라 정서에는 안맞는 영화이다청소년들이 가지고 있는 큰 고민들중 한가지를 다루고있는데 야하지도 않으면서 청소년 관람불가인게 개그이다 규모가 작은 다큐멘터리정도로 보면되겠다',
 '호세는 왜 나온건가 속었더',
 '격투액션의 최고의 걸작누구도 흉내낼수 없는 액션많이들 따라 할려고 애쓰지만 허접했던많은 양놈들 액션영화에 경전과 같은 영화',
 '난 일본정서랑 안맞는듯 보는 유치해',
 '따뜻하고 잔잔해요 좋네요',
 '쓰레기다',
 '파치노만으로 충분한',
 '제대로 된 게임을 하려면 관객들을 즐겁게 해야지 영화 안의 사람들만 즐거워서는 안된다',
 '으어어어어어어어엉무섭다 무서워 점',
 '지금까지봣던드라마중에 손가락안에드는 드라마 배우들연기력도 뛰어납니다',
 '김승우는 잘생긴 얼굴에 리더십도 대단한 남자다남자가 봐도 매우 호감가는 훈남이다',
 '왕조현을 가장 예쁘게 찍어놓은 영화',
 '으아아아아아 평점 떨어진다아아아 운지이런 영화의 목적이야 뻔하지 아니한가 계속 그렇게 세상탓하면서 살아라 망상주의자들',
 '에도 몇달안에 나올듯 ',
 '어렸을때 아부지가 빌려온 비대오로 함께 봤었는데 다시보고싶은데구할수가없네 ',
 '마지막 장면은 음악으로 의도는 보이지만 도통 이해 할 수 없다',
 '이 영화는 진짜 아름다운 영화다 이렇게 아름다운 영화를 만들수 있다는것에 놀랐다',
 '설렜던 첫 만남 벚꽃이 피던 봄 하지만 아무리 밀어내도 겨울은 결국 오기마련이죠 사랑의 아픔은 사랑으로밖에 치료할 수 없어요 썸머는 나쁜 여자가 아니에요 나쁜건 단 하나 그녀와 제가 인연이 아니란 사실뿐이죠',
 '사는게 다그런거지 뭐 난 그냥 우디알렌이 좋다',
 '세상에 이런게영화라니야하지도않고',
 '기존 세계관의 심각한 훼손과 방향을 잃은 주제 의식뿐 아니라 발전 없는 퀄리티까지 기존의 팬이라면 보고 후회함',
 '완전반하고반한영화제레미 나이가들어도 넘 섹쉬해',
 '걍 둘다 변태',
 '감독이 여자다보니 기량이 많이 딸리네',
 '끝난다는 사실이 너무 슬퍼요 가슴이 뻥 뚫려버린것같아',
 '러브오브시베리아 두 편다 너무 짠한 영화',
 '번봤어요이런 영화 또 없나요 정말 재밌어요',
 '점이 적당 아무리 배우들이 영화계의 토토가여도 스토리가 너무 쓰레기집에서 유플러스  원에 봤는데도시간이 아깝다',
 '완전 짱이었던 영화 아직까지 기억에 남아있는 재밋는 영화',
 '어설프고 흉내낸 듯한 스릴러',
 '마지막에 미란이가 코난 손 잡을 때 눈물나 ',
 '배제기 팬클럽회장해야겠다',
 '너무재밋는데 흥행이왜안됫을까요',
 '교훈과 로맨스를 동시에 갖춘 영화',
 '어릴떄 비디오 빌려본 기억난다  잼께 본듯함 잘 모르겠지만',
 '글쎄 특색도 없고 별로였던 걸로 기억하는데',
 '싸이킥에 오컬트를 더한것도 끌고가기 벅찬데 살인교사전문직수호령복선에 반전까지 더하려니 아주 맛이 가관이다연기를 썩 잘하는 배우들은 아니지만 배우가 아깝다는 생가이 심히 든다',
 '레이프 파인즈 연기 인생 중 최악의 영화가 분명하다',
 '주인공들의 순수한 사랑이 정말 아름다운 영화',
 ' 가수들이 얼마나 힘든 연습생 기간을 걸쳐 데뷔하여 지금의 큰 가수가 되었는지 잘 알게 되었고 가수들이 존경스러워지는 영화였습니다 우리나라 가수들은 대단한 것 같네요',
 '정말 오랫동안 회자될영화 배우들의 캐스팅도 신의 한수',
 '아프리카를 배경으로 한 이런 멋진 영화가 과연 다시 나올 수 있을까',
 '이게뭐야배우들이 아깝다 도통 무슨내용인지영화 귀여워 이후 최악인듯',
 '점가까이 준사람들은 나만죽을수없다 같이죽자는 물귀신작전인가 넘웃겨서 배아퍼 ',
 '극본 연출 연기가 모두 최고인 드라마 특히 주지훈의 연기가 완전 압도적',
 '좋다',
 '모든 일본문화가 들어가 있다고 할 수 있을까 최고의 사극',
 '이영화 보지마  졸라재미없어 ',
 '나니아 연대기 다음편 년에 나온다던데',
 '그만좀 끌고 이제 끝내라 지겹다 지겨워',
 '케이샤양 연기 너무 잘해요 관심 많이 가져주시길',
 '빠름과 느림 사이 힐링의 시간',
 '여자배우가 다른 사람 이었다면',
 '완전 재미있었어요아주 웃겼음',
 '진짜잼났음다시보기해도잼나고',
 '내가 평점주기전엔 인데 이거 솔직히 점대 중반은 충분히 되어야 하는거 아닌가 진짜 이것들이',
 ' 두개도 너무 유명하고 명장면패러디도 많고 우선은 연출자체가 너무 재미있다',
 '웨슬리웨슬리웨슬리',
 '내용이 연결도 안되고 결말은 뭐임',
 ' 전기세가 아깝다',
 '아그냥 답답 뭐싸우는 대사뿐이고 에혀',
 '근데 코엔형제는 어디갔지',
 '속도감 있는 레이싱 장면이 보기 좋았다 달팽이가 능력을 얻어 레이싱을 한다는 발상이 재밌는 것 같다 갑자기 주파수가 잡히면서 음악나오는게 웃겼음 ',
 '좋은 영화 같나요',
 '한숨만나옵디다',
 '흥미진진하고 재밌었습니다 좋네요',
 '기때부터 슬슬 지루하더니 극장판은 기대하고 봤건만 내용 분의가 이미 기에서 본내용이네  전부 스킵했더니 분만에 다 봤다',
 '진짜 왜 만들엇냐 시간이 아까웠다',
 '팝스타 시즌 재미없어',
 '그냥 적당히 봐 줍시다 그리고 알리사가 나오니까',
 '몽타쥬 기법의 본보기를 보여준다',
 '좋은소재 못 살린  감독 연출만 잘 했어도 대단한 영화가 되었을텐데쯧쯧',
 '좋은 소재였는데 공포 말고 좀 더 적으로 만들었다면 흥미로웠을 꺼 같다 아무 이유 없이 사람들 죽이다가 끝나버리니 싱겁다',
 '시간 분정도의 시간을 버린기분 로버트 패틴슨의 연기력만은 훌륭하다',
 '징그러워도 재밌음',
 '재미 있어요',
 '몬스터 주식회사  재밌게 봤다',
 '제작자가 평점을 달면서 영화를 본사람들을 비하하는 불편한 진실',
 '막대한 제작비를 들였지만 내용은 년대 액션으로 치중했고 그냥 킬링타임용',
 '요즘연하남들이다정신 나간줄아는 또 하나의 식상한드라마이혼한 작가들의로망아냐 ',
 '이런 쓰레기영화 만들지마라시간아깝다',
 '하여튼 허구헌날 조폭이야  개쓰기 한국영화의 현실 가족영화까지 조폭을 끌어다 붙이냐 ',
 '아 정말 몇년만에 영화다운 영화를 본건지 모르겠네요저는 탄탄한 스토리보다도 슬로우모션이나 신의 위대한능력이런거에감탄받아서 처음으로 영화평도 써보네요 평점이 왜 점도안되는지 이해가 여튼 겁나겁나 재미잇게 보고갑니다',
 '부디 좋은 영화 좀 보고싶네',
 '그래서 하고 싶은 이야기가 뭔대',
 '미친영화 소름돋는 연출과 배우들의 연기력',
 '개그맨 공채시험 차도 합격못할 유아기 개그',
 '서영희는 정말 미친년일지도 모른다 그만큼 역활 그 이상을 보여준 명연기자',
 '최고의 드라마',
 '한번쯤 이 여인들처럼 떠나보고 싶어지게 하는 영화',
 '초등학생 그림 일기을 옮겨다 놓은거 같네 안습이다 그저',
 '수많은 혹평에도 흔들릴 수 없었던',
 '다시는 저런일이 생기지 않길',
 '유치 빤스',
 '마지막장면 노래랑 장면이 너무슬펏다',
 '로드리게스 영화 중 최고반데라스 최고셀마 최고음악 쩔고 액션 쩔고',
 '연기력스토리 최악 결말은 더최악',
 '진짜 세라는게 아쉬움  그닥 야한장면도 없는데 최근에 본 영화중에 가장 작품성이 높았다는 생각이 듭니다',
 '평점이 왜이렇게조쉬하트넷좋아하지만 기무라가 더 멋있었다',
 '반전 알고나서 봤고 오줌싼줄은 몰랐다',
 '꿀잼 특히 소유랑 서인영매력터져',
 '영화는 지루하고 설득력은 제로',
 '배우들 연기도 잘하고 재미있어요만보때가 제일 재미있었구요',
 '제목이 파인딩 포레스트가 아니라 더 윈도우 맨이었으면 의미도 있고 더 잘 어울렸겠지만 흑인소년예비작가가 백인노인기성작가와 만나 교감을 나누며 함께 성장하는 것이 인상적인 울림을 줬던 영화',
 '평점이 이해가안된다솔직히 용의자보다 더 재밌는데',
 '최악의 영화 일단 배우들 외모가 안되고 연기도 그렇고 스토리는 진짜 어디다 빼먹은지 모르는 영화임만약 애니 원작을 봤다면 절대 보지 말고 원작을 안 본 사람이면 봐도 되는데 돈은 아까울 꺼임 애니 한 번더 정주행 해야 겠다',
 '그랜드 부다페스트 호텔을 그대로 베끼는게 가 지향하는 문화창조인지',
 '난 괜찮았음 연기도 열심히하는게 눈에보이고',
 '어휴 다큐멘터리 보는줄',
 '점을 주고 싶으나 없기에 반올림해서 준다그나저나 명작은 명작일세',
 '열자까지 쓸 필요가 없다 최고다',
 '내용을 세워 저예산으로 만들은것 같은데 반전부터 어수룩한듯',
 '한석규는 띄웠지만 싸구려다',
 '실화를 이정도 표현했음 잘했다만 조금 아쉽네요 이도저도 아닌 느낌이랄까',
 '년이 지난 영화인데도 지루함없이 볼 수 있다 인간의 욕망과 어리석음 잔인함 불쌍한 마농의 가족들',
 '당신이 생각하는 그런 영화가 아닙니다 그래서 너무 지루합니다 평론가 김종철님의 의견에 강추 날립니다',
 '이 영화전까진 크리스 오도넬 괜찮았었는데',
 '제목만 들어도 이미 전설이 되버린 불멸의 명작',
 '간만에 좋은영화 봤다포스터보고제목보고 처음에 속았다는 느낌이였지만 매력넘치는영화다 내용이 생뚱맞으면서도 무슨소리진 이해가 안갈듯하면서도 모든게 딱딱들어맞는내용의허점이 안보이는 희안한영화다영화가 끝나고도 찝찝함이 남지않는 깔끔한영화인거같다',
 '조성하씨가 사건에 몰입할 수 있었던 좀 더 구체적인 이유가 아쉬운거 빼고는 다 좋았어요 특히 김민희씨 연기가 인상적이었습니다 차경선 같은 인물이 존재할 것 같아서 가슴아프고 슬픈여운이 남는 영화네요',
 '년 지금까지 나온 파라노말 시리즈 중 최악이 아닌가 싶다 감독의 능력이 의심됨',
 '초등학교때 이거보고 변기 물내려가는것도 무서웠다는',
 '정말 명작이라고 생각하는 영화중 하나',
 '요즘 초딩들은 절대 모른다이 영화가 얼마나 위대한지',
 '가레스베일 관련된영화아님 이거 고로 점',
 '조승우와 수애의 연기력에 눈물 좀 흘렸네요 잘 봤습니다',
 '지금 케이블에서 하길래 검색  홍학표 방가  겨우 년된 영화라니 안습',
 '아직도 생각나는 드라마',
 '평점 점도 아까워 처참하게 허술한 스토리진짜 등장인물들이 다 붕어 아이큐가 아닌가 싶은다 잡아놓은 범인을 어처구니없는 설정으로 다시 놓치고 놓치고 놓치고딱 유아용 만화 스토리같은 수준보고나서 짜증과 드러운 기분을 느끼는 영화',
 '전작에 비해 떨어지는건 사실이지만 쓰레기 한국영화도 점대 별로없는데 헐니들 너무하다',
 '왜 세 관람가지',
 '뭐하자는거냐',
 '우베볼은 법을 농락했고 박희준은 종교계를 농락했다',
 '최고',
 '년의 작품이라는 것이 놀라운 따름',
 '볼만한데 점수가 형편없구만 그다지 변태스럽지도 않구만',
 '멍청한 연기 빈약한 상상력 야하지도 웃기지도 않는 장난',
 '맥라이언의 새로운 모습 나는 그녀의 나이 듦이 좋다',
 '무서우라고 만든 영화는 아닌 듯최소점짜리 영화',
 '소파에 죽 치고 앉아 지켜 볼 이유가 없는 작품',
 '다운받아서 봤는데 정말 비추내용도 완전 아동용 애니매이션 수준이 아니고 심오함그러니까 내용은 사라진 가족을 구하려고 떠난건데중간중간 꿈 장면은 도무지 이해가 안감 그럼 처음부터 다 부도리의 꿈인건가결론은 걍 고양이들이 귀여웠다',
 '매우 공포스럽고 잔인하고 잘 만든영화 쏘우보다 더 재미있네',
 '너무 따뜻한 드라마',
 '분노가 치밀어 오르는',
 '저양반나오는영화는 내취향하고는 정말아닌가보다',
 '전 이영화가 무슨영환줄모르고 나와서 봤는데 재밌어요야이런씨세이야',
 '대강',
 '한국영화 역대 핵노잼 영화',
 '한주한주 봤다고 하면 나도 점수를 안줬겠지만 한번에 몰아서보니 정말 잼게 봤다 초반 아역기간이 넘 긴거 빼고는 멜로 긴장감 쫄깃쫄깃 하니 좋았다',
 '아 진짜 조금만 더 손 좀 보면 왠만한 상업 영화 못지 않게 퀄리티 쩔게 만들어 질 수 있었는데 아쉽네요 그래도 충분히 재미있었습니다 개인적으로 조금만 더 잔인하게 더 자극적으로 노출씬도 화끈하게 했더라면 어땠을까 하는 국산영화라 많이 아낀 듯 보임',
 '이건 뭐별 반개도 아깝',
 '다른건 몰라도 전쟁을 통해 희생된 수많은 사람들의 눈물이 정말 뭐가 되는건지',
 '인상적인 영화였다',
 '그 마지막 장면을 위해분을 투자했던가제길',
 '제작된지 년이 지났지만 지금 봐도 감동은 여전하다',
 '볼때 쌍욕하면서 봤던영화',
 '전형적인 할리우드 영화 화려하지만 볼건 많지만 하나도 이해 안되고 재미가 없다',
 '내용 진짜 뻔한데 볼만함',
 '하',
 '고현정 어제 진행도 좋고 너무 이뻤어요',
 '아직까지 이런 스케일의 한국영화는 놈놈놈 이후로 없었으므로 당연 점',
 '정말정말정말정말정말정말정말 재밌다 영화보면서 가슴이 두근거려본건 처음이다 명장면이 잊혀지질않는다',
 '넘 좋은',
 '여주인공두 색시하고 넘 잼있다',
 '정말 고생하셔서 멋있고재미있는드라마만들어주셔서감사합니다',
 '좀더러운 장면도 없진 않으나 당연히 점 만점에 점이죠안나 켄드릭의 새로운 발견을 절대 놓쳐선 안됩니다',
 '유지태의 캐릭터에 대한 설명을 제외하곤 나머지 캐릭터에 대한 설명이 지나치게 불친절해서 몰입도가 심하게 떨어진다',
 '사망유희 보단 훨낫다 액션도 깔끔하고 편집도 괜찮고',
 '진짜 재미도 없고 감동도 없다 다만 요즘 애들의 수준을 엿볼수 있다 마약 유흥 유명인사가 갖고 다니는 값비싼 옷과 구두에 관심이 있고 절도같은 범죄에 대해 전혀 죄의식이나 죄책감이 없는 애들 한국도 마찬가지',
 '아니 이 애니를 보고 쓰레기라고 하는 분들 머릿속은 도대체 멀로 이루어져있는지',
 '뭔가 돈을 버린것같은 기분이 드는 영화 노답',
 '여기가 그개구라쳤다던 그 의젖 선생님 그영화맞나요',
 '정말 정말 재밌었어요',
 '한장의 사진으로 세상을 깨운다 생생한 리얼리티가 감동을 더해주네요',
 '후속작 영환가 뭐지 이건',
 '공포아님니다 드라마입니다',

- Hugging Face Dataset 객체로 변환

In [10]:
# Hugging Face 전용 Dataset 객체로 변환하기
# Dataset : 대용량 텍스트 데이터를 효율적으로 다룰 수 있게 도와주는 도구

from datasets import Dataset

train_dataset = Dataset.from_dict({'document': train_texts,
                                   'label': train_labels})
val_dataset = Dataset.from_dict({'document': val_texts,
                                 'label': val_labels})

In [11]:
train_dataset

Dataset({
    features: ['document', 'label'],
    num_rows: 16000
})

# 3가지 타입의 한국어 언어모델
- Encoder 중심의 모델 : BERT 계열

<table>
<tr align="center">
  <td width="50"><b>모델명</b>
  <td width="50"><b>개발자</b>
  <td width="100"><b>학습데이터</b>
  <td width="100"><b>Tokenizer</b>
  <td width="100"><b>단어수</b>
  <td width="50"><b>파라미터수</b>
<tr align="center">
  <td>KorBERT
  <td>ETRI
  <td>뉴스/백과사전<br>23GB
  <td>Mophologpy,<br>WordPiece
  <td>30,349(Mophologpy),<br>30,797(WordPiece)
  <td>110M
<tr align="center">
  <td>KoBERT
  <td>SKT
  <td>위키피디아<br>20M
  <td>Sentencce-Piece
  <td>8,002
  <td>92M
<tr align="center">
  <td>HanBERT
  <td>투블럭AI
  <td>일반/특허문서<br>70GB
  <td>Moran
  <td>54,000
  <td>128M
<tr align="center">
  <td>KoreALBERT
  <td>삼성SDS
  <td>위키피디아/나무위키/뉴스<br>책 줄거리 요약 등<br>43GB
  <td>Sentencce-Piece
  <td>32,000
  <td>12M, 18M
<tr align="center">
  <td>KLUE-BERT
  <td>Klue project
  <td>모두의말뭉치/CC-100-Kor/<br>나무위키/뉴스/청원 등<br>63GB
  <td>Morpheme-based<br>subword
  <td>32,000
  <td>111M
<tr align="center">
  <td>KRBERT
  <td>서울대
  <td>위키피디아/뉴스
  <td>WordPiece
  <td>16,424(Character)<br>12,367(Subcharacter)
  <td>99M(Character)<br>96M(Subcharacter)
<tr align="center">
  <td>DistillKoBERT
  <td>개인(박장원)
  <td>위키피디아/나무위키/<br>뉴스 등
  <td>Sentence-Piece
  <td>30,522
  <td>27.8M
<tr align="center">
  <td>KcBERT
  <td>개인(이준범)
  <td>네이버뉴스의 댓글/대댓글
  <td>Word-Piece
  <td>30,000
  <td>109M
<tr align="center">
  <td>KcELETRA
  <td>개인(이준범)
  <td>네이버뉴스의 댓글/대댓글
  <td>Word-Piece
  <td>30,000
  <td>124M
<tr align="center">
  <td>KoBigBird
  <td>개인(박장원)
  <td>위키피디아/뉴스/모두의<br>말뭉치/Common Crawl 등
  <td>Word-Piece
  <td>32,500
  <td>113.8M                   
</table>

- Decoder 중심의 모델 : GPT 계열

<table>
<tr align="center">
  <td width="50"><b>모델명</b>
  <td width="50"><b>개발자</b>
  <td width="100"><b>학습데이터</b>
  <td width="100"><b>Tokenizer</b>
  <td width="100"><b>단어수</b>
  <td width="50"><b>파라미터수</b>
<tr align="center">
  <td>KoGPT2
  <td>SKT
  <td>위키피디아, 뉴스, 나무위키,<br>네이버영화리뷰<br>한국어 Common Crawl<br>152M
  <td>Character BPE
  <td>51,200
  <td>125M
<tr align="center">
  <td>KoGPT-Trinity
  <td>SKT
  <td>Ko-DATA dataset<br>1.2B
  <td>-
  <td>51,200
  <td>1.2B
<tr align="center">
  <td>HyperCLOVA
  <td>NAVER
  <td>뉴스/카페/블로그/지식in/<br>웹문서/댓글 등 네이버<br>수집문서, 모두의 말뭉치<br>위키피디아 등<br>562B
  <td>Morpheme-aware byte-<br>level BPE
  <td>-
  <td>82.0B
<tr align="center">
  <td>KoGPT
  <td>Kakaobrain
  <td>200B
  <td>-
  <td>64,512
  <td>6.0B
</table>

- Encoder-Decoder 모델 : Seq2Seq 계열

<table>
<tr align="center">
  <td width="50"><b>모델명</b>
  <td width="50"><b>개발자</b>
  <td width="100"><b>학습데이터</b>
  <td width="100"><b>Tokenizer</b>
  <td width="100"><b>단어수</b>
  <td width="50"><b>파라미터수</b>
<tr align="center">
  <td>KoBART
  <td>SKT
  <td>위키피디아/뉴스/모두의<br>말뭉치/청와대 국민청원 등<br>0.27B
  <td>Character BPE
  <td>30,000
  <td>124M
<tr align="center">
  <td>KE-T5
  <td>KETI
  <td>한국어와 영어 데이터가<br> 7:3의 비율인 데이터<br>30GB
  <td>Sentence-Piece
  <td>64,000
  <td>247M
<tr align="center">
  <td>ET5
  <td>ETRI
  <td>위키피디아/뉴스/방송<br>대본/영화 드라마 대본 등<br>136GB
  <td>Sentence-Piece
  <td>45,100
  <td>60M
<tr align="center">
  <td>EXAONE
  <td>LG AI연구원
  <td>말뭉치 600B, 이미지,<br>텍스트 Pair 데이터 250M이상
  <td>-
  <td>-
  <td>300B
</table>

- 대표적인 Transformer 모델

<center>  
<img src="https://arome1004.cafe24.com/images/deeplearning/transformer_model01.png" width=60%>   
</center>

- 허깅페이스 로그인

# KoBERT
- 2019년에 SKT Brain에서 공개
- 한국어 자연어 처리를 위해 최적화된 BERT(Bidirectional Encoder Representations from Transformers) 기반 모델
- KoBERT는 BERT 모델을 한국어 데이터로 사전 학습하여, 한국어의 미묘한 문맥과 의미를 더 잘 파악할 수 있도록 만들어진 라이브러리

### Hugging Face Fine Tuning 워크 플로우
> 데이터 → Tokenizer → DataCollator → Model → Trainner → 결과

1. 토크나이저
: 문장을 쪼개는 가위
- 사전학습때 사용된 토큰화 도구를 사용해서 입력 데이터 처리

2. 데이터 콜레이터
: 규격화된 통
- 입력 데이터를 일정한 크기로 맞춰줌(패딩 처리 등)

3. Trainner
: 관리자
- 데이터 전처리 ~ 학습, 평가, 저장까지 모든 과정을 한 번에 수행해주는 고수준 API

4. Training Arguments
- 학습 과정에서 필요한 하이퍼 파라미터들을 설정하는 클래스
- 학습률, 배치 크기, 에포크 등 학습 관련된 설정값을 관리

5. Downstream Task Classes
- fine tuning 대상 모델
- 사전 학습된 모델을 다양한 task에 맞게 활용할 수 있음

In [ ]:
# https://huggingface.co/monologg/kobert

- 토큰화 / 인코딩

In [13]:
# BERT용 토큰화 도구 가져오기
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("monologg/kobert")


# 토큰화 함수 정의 (자:어떻게 변환할지 규칙 설정)
def tokenize_function(examples):
    # padding='max_length' : max_length를 padding 길이로 설정
    # truncation=True : max_length보다 크면 자름
    # max_length=128  : 문장의 최대 길이
    return tokenizer(examples["document"],# 영화 댓글 텍스트 컬럼
                     max_length=128,  # 모든 문장을 128 토큰으로 통일
                     padding='max_length',# 짧은 문장은 0으로 채워서 max_length(128)에 맞춤
                     truncation=True)# 128보다 긴 문장은 128에서 잘라냄
# 토큰화 수행
# 훈련 데이터 전체에 토큰화 함수 적용
train_dataset1 = train_dataset.map(tokenize_function,
                                   batched=True) # 한 번에 여러 문장씩 처리해서 속도 향상

# 검증 데이터 전체에 토큰화 함수 적용
val_dataset1 = val_dataset.map(tokenize_function,
                               batched=True)

tokenizer_config.json:   0%|          | 0.00/263 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt:   0%|          | 0.00/77.8k [00:00<?, ?B/s]

Map:   0%|          | 0/16000 [00:00<?, ? examples/s]

Map:   0%|          | 0/4000 [00:00<?, ? examples/s]

- 모델 훈련

In [15]:
# HuggingFace transformers에서 텍스트 분류용 모델 가져오기
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "monologg/kobert", # 모델명
    num_labels=2 # 분류할 클래스 개수 (이진분류 - 긍정/부정)
)

config.json:   0%|          | 0.00/426 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  369MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: monologg/kobert
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [16]:
# HuggingFace의 학습 도구들 가져오기
# TrainingArguments = 학습 설정값 모음
# Trainer = 실제 학습을 실행하는 도구
from transformers import TrainingArguments, Trainer

# DataCollatorWithPadding:배치 내 패딩을 자동으로 처리해주는 도구
from transformers import DataCollatorWithPadding

In [17]:
# DataCollatorWithPadding()
# 같은 배치(batch) 내에서 가장 긴 문장의 길이에 맞춰
# 나머지 짧은 문장들의 뒤에 패딩(padding) 토큰을 자동으로 채워주는 기능
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# 학습 설정값 정의
training_args = TrainingArguments(
    output_dir='./results/kobert_naver', # 학습된 모델 저장할 폴더
    learning_rate=2e-5,# 학습률 0.00002 # W값을 한 번에 얼마나 업데이트할지  # 너무 크면 학습 불안정, 너무 작으면 학습 느림
    weight_decay=0.01,# 학습률 감쇄 # 과적합 방지용 (W값이 너무 커지지 않게)
    per_device_train_batch_size=16, # 훈련 데이터 배치 사이즈 # 훈련할 때 한 번에 16개 문장씩 처리
    per_device_eval_batch_size=16, # 검증 데이터 배치 사이즈 # 검증할 때 한 번에 16개 문장씩 처리
    num_train_epochs=1,# 학습 반복 수 # 전체 데이터를 1번 반복 학습 (데이터 전체를 1바퀴 돔) # 자:16배치* 1,250번 = 20,000개 데이터 (1바퀴)
    eval_strategy="epoch",# 검증/저장 시기 # 1 epoch마다 검증 데이터로 성능 측정
    save_strategy="epoch",# 베스트 모델 저장 여부 # 1 epoch마다 모델 저장
    load_best_model_at_end=True, # 학습 끝나면 가장 성능 좋은 모델 불러오기
    report_to = "none" # 모니터링 도구 사용 안함
                        # wandb (인공지능이 학습할 때 점수(Loss)가 예쁘게 잘 떨어지고 있는지, 정확도(Accuracy)는 올라가고 있는지를 실시간으로 확인)같은 모니터링 도구 사용 안 함
)

# Trainer 설정
# 모델, 학습설정, 데이터를 한 곳에 묶어주는 것
trainer = Trainer(
    model=model, # 학습할 모델 (KoBERT)
    args=training_args, # 위에서 설정한 학습 설정값
    train_dataset=train_dataset1, # 훈련 데이터(자: 문제집)
    eval_dataset=val_dataset1, # 검증 데이터(자:모의고사 문제집)
    data_collator=data_collator # 배치 패딩 처리 도구(자:보조코치)
)

# 학습 시작!
# 위 설정대로 KoBERT를 네이버 영화 댓글로 파인튜닝
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1000, training_loss=0.6965595397949219, metrics={'train_runtime': 381.7197, 'train_samples_per_second': 41.916, 'train_steps_per_second': 2.62, 'total_flos': 1052444221440000.0, 'train_loss': 0.6965595397949219, 'epoch': 1.0})

- 예측

In [19]:
from transformers import pipeline

model2 = pipeline(
    task="text-classification",
    model='./results/kobert_naver/checkpoint-1000/',
    tokenizer=tokenizer
)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [21]:
model2("아 정말 감동적이고  아름다운 영화에요")

[{'label': 'LABEL_0', 'score': 0.5034354329109192}]